name: Merge Resume into Template

on:
  workflow_dispatch:
    inputs:
      resume_filename:
        description: 'Filename of the resume in resumes/ (e.g., resume.docx)'
        required: true
        default: 'resume.docx'
      template_filename:
        description: 'Filename of the template in templates/ (e.g., template.docx)'
        required: true
        default: 'template.docx'
      output_filename:
        description: 'Filename for the output (e.g., output/merged_resume.docx)'
        required: true
        default: 'output/merged_resume.docx'

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run merge script
        run: |
          python main.py "templates/${{ github.event.inputs.template_filename }}" \
                         "resumes/${{ github.event.inputs.resume_filename }}" \
                         "${{ github.event.inputs.output_filename }}"

      - name: Upload merged document
        uses: actions/upload-artifact@v3
        with:
          name: merged-resume
          path: ${{ github.event.inputs.output_filename }}
